# Generated by Django 4.0.3 on 2022-04-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, db_column='Country Code', max_length=3, null=True, verbose_name='Country Code')),
                ('region', models.CharField(blank=True, db_column='Region', max_length=150, null=True, verbose_name='Region')),
                ('income', models.CharField(blank=True, db_column='Income Group', max_length=150, null=True, verbose_name='Income Group')),
                ('special_notes', models.CharField(blank=True, db_column='Special Notes', max_length=150, null=True, verbose_name='Special Notes')),
                ('table_name', models.CharField(blank=True, db_column='Table Name', max_length=150, null=True, verbose_name='Table Name')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'db_table': 'Metadata-Countries',
            },
        ),
    ]
